# Ensure the following values are set in a .env file:
#   * PUID
#   * PGID
#   * TZ
#   * STORAGE_DIR
#   * CONFIG_DIR
#   * LOCAL_NETWORK
#   * DOMAIN

x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

services:
  qbittorrent:
    container_name: qbittorrent
    image: "cr.hotio.dev/hotio/qbittorrent:latest"
    environment:
      <<: *default-tz-puid-pgid
      UMASK: 002
      VPN_ENABLED: "true"
      VPN_CONF: wg0
      VPN_IP_CHECK_DELAY: 5
      VPN_LAN_NETWORK: ${LOCAL_NETWORK}
    volumes:
      - "${CONFIG_DIR}/qbittorrent:/config:rw"
      - "${CONFIG_DIR}/qbittorrent/iQbit:/app/iQbit:rw"
      - "${STORAGE_DIR}/torrents:/data/torrents:rw"
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      - traefik.enable=true
      - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080
      - traefik.http.routers.qbittorrent-rtr.rule=Host(`downloads.${DOMAIN}`)
      - traefik.http.routers.qbittorrent-rtr.entrypoints=websecure
      - traefik.http.routers.qbittorrent-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.qbittorrent-rtr.middlewares=ipwhitelist-mddl@docker
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
  radarr:
    container_name: radarr
    image: "cr.hotio.dev/hotio/radarr:nightly"
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${CONFIG_DIR}/radarr:/config:rw"
      - "${STORAGE_DIR}:/data:rw"
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      - traefik.enable=true
      - traefik.http.services.radarr-svc.loadbalancer.server.port=7878
      - traefik.http.routers.radarr-rtr.rule=Host(`movies.${DOMAIN}`)
      - traefik.http.routers.radarr-rtr.entrypoints=websecure
      - traefik.http.routers.radarr-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.radarr-rtr.middlewares=ipwhitelist-mddl@docker
  sonarr:
    container_name: sonarr
    image: "cr.hotio.dev/hotio/sonarr:latest"
    restart: unless-stopped
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${CONFIG_DIR}/sonarr:/config:rw"
      - "${STORAGE_DIR}:/data:rw"
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      - traefik.enable=true
      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr-rtr.rule=Host(`tv.${DOMAIN}`)
      - traefik.http.routers.sonarr-rtr.entrypoints=websecure
      - traefik.http.routers.sonarr-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.sonarr-rtr.middlewares=ipwhitelist-mddl@docker
  prowlarr:
    container_name: prowlarr
    image: "cr.hotio.dev/hotio/prowlarr:nightly"
    restart: unless-stopped
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${CONFIG_DIR}/prowlarr:/config:rw"
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      - traefik.enable=true
      - traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr-rtr.rule=Host(`indexers.${DOMAIN}`)
      - traefik.http.routers.prowlarr-rtr.entrypoints=websecure
      - traefik.http.routers.prowlarr-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.prowlarr-rtr.middlewares=ipwhitelist-mddl@docker
  overseerr:
    container_name: overseerr
    image: "cr.hotio.dev/hotio/overseerr:latest"
    restart: unless-stopped
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${CONFIG_DIR}/overseerr:/config:rw"
      - "${STORAGE_DIR}/media:/data/media:rw"
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      - traefik.enable=true
      - traefik.http.services.overseerr-svc.loadbalancer.server.port=5055
      - traefik.http.routers.overseerr-rtr.rule=Host(`requests.${DOMAIN}`)
      - traefik.http.routers.overseerr-rtr.entrypoints=websecure
      - traefik.http.routers.overseerr-rtr.tls.certresolver=letsencrypt
  monitor:
    container_name: monitor
    image: amir20/dozzle:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
      - traefik.enable=true
      - traefik.http.services.monitor-svc.loadbalancer.server.port=8080
      - traefik.http.routers.monitor-rtr.rule=Host(`monitor.${DOMAIN}`)
      - traefik.http.routers.monitor-rtr.entrypoints=websecure
      - traefik.http.routers.monitor-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.monitor-rtr.middlewares=ipwhitelist-mddl@docker
  traefik:
    image: "traefik:latest"
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--api"
      - "--api.dashboard=true"
      - "--metrics=true"
      - "--metrics.prometheus=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesResolvers.letsencrypt.acme.storage=/config/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.tlschallenge=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${CONFIG_DIR}/traefik:/config:rw"
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
      - "traefik.enable=true"
      - "traefik.http.middlewares.ipwhitelist-mddl.ipwhitelist.sourcerange=127.0.0.1/32,${LOCAL_NETWORK}"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traffic.${DOMAIN}`)"
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-rtr.entrypoints=websecure"
      - "traefik.http.routers.traefik-rtr.middlewares=ipwhitelist-mddl@docker"
      - "traefik.http.services.traefik-svc.loadbalancer.server.port=8080"
